name: Compile Wiki.GG Redirect Extension

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - run: npm ci

      - name: Compile scripts
        run: npm run build

      - name: Create packages
        run: npm run package-dev

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: pkgs/*.zip
